// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_NirzyGzhe_NkGrSbRT1Vxb4ibIziEk',
    appId: '1:209545218765:web:56378f711685e1500cf784',
    messagingSenderId: '209545218765',
    projectId: 'a-schoolapp',
    authDomain: 'a-schoolapp.firebaseapp.com',
    storageBucket: 'a-schoolapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBs-7leqsl1CMW2lXjf0V8EP7EealIgYY',
    appId: '1:209545218765:android:0b3c7cdacac0fc7e0cf784',
    messagingSenderId: '209545218765',
    projectId: 'a-schoolapp',
    storageBucket: 'a-schoolapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLImFaKLRmAxiKzJS7NVeqy_9ouVvvr8',
    appId: '1:209545218765:ios:d5b9a9c4e6dd4fe50cf784',
    messagingSenderId: '209545218765',
    projectId: 'a-schoolapp',
    storageBucket: 'a-schoolapp.appspot.com',
    iosBundleId: 'com.example.uLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLImFaKLRmAxiKzJS7NVeqy_9ouVvvr8',
    appId: '1:209545218765:ios:ebca30df4c0749120cf784',
    messagingSenderId: '209545218765',
    projectId: 'a-schoolapp',
    storageBucket: 'a-schoolapp.appspot.com',
    iosBundleId: 'com.example.uLearning.RunnerTests',
  );
}
